# Generated by Django 2.1.15 on 2021-10-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210919_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('made_on', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='FileData',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='date_time',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='Average_fuel_consumption',
        ),
        migrations.AddField(
            model_name='file',
            name='Driver_Type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
