# Generated by Django 2.1.15 on 2021-10-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211009_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Promise',
        ),
    ]
